### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by dodoaska** [herwonowr/exprolog#3]
┌──(asus㉿cyber)-[~/exprolog]
└─$ python exprolog.py -t https://192.168.1.2
  File "exprolog.py", line 423
SyntaxError: Non-ASCII character '\xe2' in file exprolog.py on line 424, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
                                                                                                                            
┌──(asus㉿cyber)-[~/exprolog]

**Comment by dodoaska** [comment]
┌──(asus㉿cyber)-[~/exprolog]
└─$ python exprolog.py -t http://192.168.1.2                                                                        1 ⨯
  File "exprolog.py", line 423
SyntaxError: Non-ASCII character '\xe2' in file exprolog.py on line 424, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
                                                                                                                            
┌──(asus㉿cyber)-[~/exprolog]

**Comment by herwonowr** [comment]
Fixed in this patch https://github.com/herwonowr/exprolog/commit/e48c0c6ace318cd42bffae752a86c55cfe9383a5
